# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

r:
  - oldrel
  - release
  - devel
  - bioc-devel

warnings_are_errors: true
sudo: false
cache: packages

os:
  - linux

script:
  - R CMD build . --compact-vignettes=gs+qpdf
  - R CMD check *tar.gz --as-cran

addons:
  apt:
    update: true
    packages:
      - libgs-dev
      - qpdf
      - ghostscript

after_failure:
  - cat $TRAVIS_BUILD_DIR/RelDists.Rcheck/00install.out
  - cat $TRAVIS_BUILD_DIR/RelDists.Rcheck/00check.log
