name: Compress PDF document
on: [push]
jobs:
    compress_pdf:
        runs-on: ubuntu-latest
        steps:
            - name: Set up Git repository
              uses: actions/checkout@v2
            - name: Compress PDF
              uses: jy95/ghostscript-action@v1
              with:
                file: 'vignettes/maxlogL.pdf'
                output: 'vignettes/maxlogL-compressed.pdf'
                arbitrary-parameters: '-dCompatibilityLevel=1.4 -dPDFSETTINGS=/printer'
